[project]
name = "gauge-3d"
version = "0.1.0"
description = "3D reconstruction and distance measurement from video"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opencv-python>=4.8.0",
    "numpy>=1.24.0",
    "Pillow>=10.0.0",
    "tqdm>=4.65.0"
]
